### ISSUE TITLE
error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.hpp:257: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<3, 4>; VDcn = cv::Set<1>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'

### ISSUE THREAD

**Issue by sandeep-25** [arsho/local_binary_patterns#2]
Hi, I tried to find the LBP of Hyperspectral Image after computing first 3 Principal Component Analysis. I am getting the following error.
error        Traceback (most recent call last)
<ipython-input-29-11b23888190d> in <module>()
      1 img_bgr=pcdata
----> 2 img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.hpp:257: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<3, 4>; VDcn = cv::Set<1>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)

**Comment by arsho** [comment]
Closing the issue as it is not in scope of this project.
